/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PhongDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Phong;
/**
 *
 * @author Admin
 */
public class QuanLyPhong extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyPhong.class.getName());
    private static Integer idPhong = null;
    /**
     * Creates new form QuanLyPhong
     */
    public QuanLyPhong() throws SQLException {
        initComponents();
        loadDatas("", "");
    }
    
    private void resetField() {
        txtGiaPhong.setText("");
        txtTenPhong.setText("");
        txtMoTa.setText("");
        txtTimKiem.setText("");
    }
    
 
    
     private void loadDatas (String search, String cbSearch) throws SQLException {
         List<Phong> phongs = PhongDAO.getAllPhong(search, cbSearch);
          DefaultTableModel model = (DefaultTableModel) TablePhong.getModel();
           model.getDataVector().removeAllElements();
        for (Phong nv : phongs) {
            Object[] row = {nv.getId(), nv.getTen_phong(), nv.getGia_phong(), nv.getMo_ta(), nv.getTrang_thai(), nv.getNgay_them(), nv.getNgay_cap_nhat()};
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePhong = new javax.swing.JTable();
        cbTrangThai = new javax.swing.JComboBox<>();
        txtTenPhong = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtGiaPhong = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnDatPhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Mô tả");

        jLabel5.setText("Giá phòng");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý phòng");

        TablePhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tên phòng", "Giá phòng", "Mô tả", "Trạng thái", "Ngày thêm", "Ngày cập nhật"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePhong.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablePhongAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TablePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePhong);

        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa đặt", "Đã đặt", "Đang dọn" }));
        cbTrangThai.setToolTipText("");

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên phòng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel4.setText("Trạng thái");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenPhong)
                                    .addComponent(cbTrangThai, 0, 239, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaPhong)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablePhongAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablePhongAncestorAdded

    }//GEN-LAST:event_TablePhongAncestorAdded

    private void TablePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePhongMouseClicked
        int row =  TablePhong.getSelectedRow();// cột nó sẽ từ từ 0
        Integer id = (Integer) TablePhong.getValueAt(row, 0); // column trong JTable bắt đầu từ 0
        String tenPhong = (String) TablePhong.getValueAt(row, 1);
        Float giaPhong = (Float) TablePhong.getValueAt(row, 2);
        String trangThai = (String) TablePhong.getValueAt(row, 4);
        String moTa = (String) TablePhong.getValueAt(row, 3);
        txtTenPhong.setText(tenPhong);
        txtGiaPhong.setText(giaPhong.toString());
        cbTrangThai.setSelectedItem(trangThai);
        txtMoTa.setText(moTa);
        idPhong = id;
    }//GEN-LAST:event_TablePhongMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row =  TablePhong.getSelectedRow();// cột nó sẽ từ từ 0
        if (row != -1) {
            Integer rowData = (Integer) TablePhong.getValueAt(row, 0); // column trong JTable bắt đầu từ 0
            try {
                boolean isSucsess =  PhongDAO.deletePhong(rowData);
                if (isSucsess) {
                    JOptionPane.showMessageDialog(this,
                        "Xoá phòng thành công",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    loadDatas("", "");
                }else {
                    // lỗi ở csdl
                    JOptionPane.showMessageDialog(this,
                        "Xoá phòng thật bại",
                        "Inane warning",
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                    "Xoá phòng thật bại. Bạn không thể xoá phòng khi đang có người sử dụng phòng",
                    "Inane warning",
                    JOptionPane.ERROR_MESSAGE);
                System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(this, // this -> from của mình
                "Vui lòng chọn phòng cần xoá", // message
                "Cảnh báo", // title message
                JOptionPane.WARNING_MESSAGE);// type error(icon)
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        try {
            Phong phong = new Phong();
            phong.setTen_phong(txtTenPhong.getText());
            phong.setMo_ta(txtMoTa.getText());
            phong.setGia_phong(Float.parseFloat(txtGiaPhong.getText()));
            phong.setTrang_thai((String) cbTrangThai.getSelectedItem());
            boolean result = PhongDAO.createPhong(phong);
            if (result) {
                 JOptionPane.showMessageDialog(this, // this -> from của mình
                "Thêm phòng thành công", // message
                "Cảnh báo", // title message
                JOptionPane.INFORMATION_MESSAGE);// type error(icon)
                Throwable ex = null;
                loadDatas("", "");
            }else {
                JOptionPane.showMessageDialog(this, // this -> from của mình
                "Thêm phòng dùng thật bại", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
            }
          
        }catch(Exception ex) {
            // Bắt lỗi chung
            JOptionPane.showMessageDialog(this, // this -> from của mình
                "Thêm phòng dùng thật bại", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
            System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        // lỗi ở csdl
        

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         try {
             if (idPhong == null) {
                    JOptionPane.showMessageDialog(this, // this -> from của mình
                "Vui lòng chọn phòng trước khi cập nhật", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
             }else {
                Phong phong = new Phong();
                phong.setId(idPhong);
                phong.setTen_phong(txtTenPhong.getText());
                phong.setMo_ta(txtMoTa.getText());
                phong.setGia_phong(Float.parseFloat(txtGiaPhong.getText()));
                phong.setTrang_thai((String) cbTrangThai.getSelectedItem());
                boolean result = PhongDAO.updatePhong(phong);
            if (result) {
                 JOptionPane.showMessageDialog(this, // this -> from của mình
                "Cập nhật thông tin phòng thành công", // message
                "Cảnh báo", // title message
                JOptionPane.INFORMATION_MESSAGE);// type error(icon)
                Throwable ex = null;
                loadDatas("", "");
            }else {
                JOptionPane.showMessageDialog(this, // this -> from của mình
                "Cập nhật thông tin phòng thật bại", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
            }
          
         }
             
       
        }catch(Exception ex) {
            // Bắt lỗi chung
            JOptionPane.showMessageDialog(this, // this -> from của mình
                "Cập nhật thông tin phòng thật bại", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
            System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        // lỗi ở csdl
        

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            loadDatas("", "");
            resetField();
        } catch (SQLException ex) {
            System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
         String searchName = txtTimKiem.getText();
         String cbName = (String) cbTrangThai.getSelectedItem();
         
         if (!searchName.isEmpty()&& cbName.isEmpty()) {
             try {
                 loadDatas(searchName, "");
             } catch (SQLException ex) {
                 System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
         }else if (searchName.isEmpty()&& !cbName.isEmpty()) {
                try {
                 loadDatas("", cbName);
             } catch (SQLException ex) {
                 System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
         }else {
                try {
                 loadDatas(searchName, cbName);
             } catch (SQLException ex) {
                 System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
         }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new QuanLyPhong().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(QuanLyPhong.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePhong;
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
