/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.NhanVienDAO;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import utils.Common;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JFrame {
    private  Integer IdNhanVien = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName());

    /**
     * Creates new form QuanLyNguoiDung
     */
    public QuanLyNhanVien() throws SQLException {
        initComponents();
        loadDatas("");
    }
    
    
    private void loadDatas (String search) throws SQLException {
        List<NhanVien> nhanViens = NhanVienDAO.getAllNhanVien(search);
        DefaultTableModel model = (DefaultTableModel) JTableNhanVien.getModel();
        model.getDataVector().removeAllElements();
        for (NhanVien nv : nhanViens) {
            Object[] row = {nv.getId(), nv.getHo_ten(), nv.getDia_chi(), nv.getGioi_tinh(), nv.getNgay_sinh(), nv.getSo_cmnd(), nv.getNgay_vao_lam()  };
            model.addRow(row);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableNhanVien = new javax.swing.JTable();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoCmnd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayVaoLam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboGioiTinh = new javax.swing.JComboBox<>();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnTimKiem1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý nhân viên");

        JTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Họ tên", "Địa chỉ", "Giới tính", "Ngày sinh", "Số CMND", "Ngày vào làm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableNhanVien.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JTableNhanVienAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableNhanVien);

        jLabel2.setText("Họ tên");

        jLabel3.setText("Số cmnd");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Ngày vào làm");

        ComboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTimKiem1.setText("Tìm kiếm");
        btnTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Giới tính");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSoCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayVaoLam)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ComboGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(ComboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem1))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void resetDataEmpty() {
        txtDiaChi.setText("");
            txtHoTen.setText("");
            txtNgaySinh.setText("");
            txtSoCmnd.setText("");
            txtTimKiem.setText("");
            txtNgayVaoLam.setText("");
    }
    
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            loadDatas("");
           resetDataEmpty();
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(this,
                "Tìm kiếm thất bại, đã xảy ra lỗi csdl",
                "Thông báo",
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       
        try {
            NhanVien nhanVien = new NhanVien();
            nhanVien.setHo_ten(txtHoTen.getText());
            nhanVien.setDia_chi(txtDiaChi.getText());
            nhanVien.setSo_cmnd(txtSoCmnd.getText());
            LocalDate date_ngay_vao_lam = LocalDate.parse(txtNgayVaoLam.getText());
            java.sql.Date ngayVaoLam = java.sql.Date.valueOf(date_ngay_vao_lam);
            nhanVien.setNgay_vao_lam(ngayVaoLam);
            LocalDate date_ngay_sinh = LocalDate.parse(txtNgaySinh.getText());
            java.sql.Date ngay_sinh = java.sql.Date.valueOf(date_ngay_sinh);
            nhanVien.setNgay_sinh(ngay_sinh);
            nhanVien.setGioi_tinh(ComboGioiTinh.getSelectedItem().toString());
            nhanVien.setGioi_tinh(ComboGioiTinh.getSelectedItem().toString());
        
            boolean isSucsess = NhanVienDAO.createNhanVien(nhanVien);
            if (isSucsess) {
                //default title and icon
                JOptionPane.showMessageDialog(this,
                    "Thêm người dùng thành công",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                    );
                resetDataEmpty();
                loadDatas("");
            }else {
                // thêm không thành công 0
              JOptionPane.showMessageDialog(this,
                "Thêm người dùng thật bại",
                "Thông báo",
                JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            // lỗi ở csdl
            JOptionPane.showMessageDialog(this,
                "Thêm người dùng thật bại",
                "Inane warning",
                JOptionPane.ERROR_MESSAGE);
            System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch(Exception ex) {
            // Bắt lỗi chung
              JOptionPane.showMessageDialog(this, // this -> from của mình
                "Thêm người dùng thật bại", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
            System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem1ActionPerformed
        try {
            // TODO add your handling code here:
            loadDatas(txtTimKiem.getText());
        } catch (SQLException ex) {
            System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnTimKiem1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         try {
            NhanVien nhanVien = new NhanVien();
            if (IdNhanVien == null) {
                 JOptionPane.showMessageDialog(this,
                "Vui lòng chọn nhân viên trước khi sửa",
                "Thông báo",
                JOptionPane.WARNING_MESSAGE);
            }else {
                nhanVien.setId(IdNhanVien);
                nhanVien.setHo_ten(txtHoTen.getText());
                nhanVien.setDia_chi(txtDiaChi.getText());
                nhanVien.setSo_cmnd(txtSoCmnd.getText());
                LocalDate date_ngay_vao_lam = LocalDate.parse(txtNgayVaoLam.getText());
                java.sql.Date ngayVaoLam = java.sql.Date.valueOf(date_ngay_vao_lam);
                nhanVien.setNgay_vao_lam(ngayVaoLam);
                LocalDate date_ngay_sinh = LocalDate.parse(txtNgaySinh.getText());
                java.sql.Date ngay_sinh = java.sql.Date.valueOf(date_ngay_sinh);
                nhanVien.setNgay_sinh(ngay_sinh);
                nhanVien.setGioi_tinh(ComboGioiTinh.getSelectedItem().toString());
                nhanVien.setGioi_tinh(ComboGioiTinh.getSelectedItem().toString());

            boolean isSucsess = NhanVienDAO.updateNhanVien(nhanVien);
            if (isSucsess) {
                //default title and icon
                JOptionPane.showMessageDialog(this,
                    "Cập nhật người dùng thành công",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                    );
                resetDataEmpty();
                loadDatas("");
            }else {
                // thêm không thành công 0
              JOptionPane.showMessageDialog(this,
                "Cập nhật dùng thật bại",
                "Thông báo",
                JOptionPane.ERROR_MESSAGE);
            }
           }
            
        } catch (SQLException ex) {
            // lỗi ở csdl
            JOptionPane.showMessageDialog(this,
                "Cập nhật dùng thật bại",
                "Inane warning",
                JOptionPane.ERROR_MESSAGE);
            System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch(Exception ex) {
            // Bắt lỗi chung
              JOptionPane.showMessageDialog(this, // this -> from của mình
                "Cập nhật dùng thật bại", // message
                "Cảnh báo", // title message
                JOptionPane.ERROR_MESSAGE);// type error(icon)
            System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row =  JTableNhanVien.getSelectedRow();// cột nó sẽ từ từ 0
        if (row != -1) {
            Integer rowData = (Integer) JTableNhanVien.getValueAt(row, 0); // column trong JTable bắt đầu từ 0
            try {
                boolean isSucsess =  NhanVienDAO.deleteNhanVien(rowData);
                if (isSucsess) {
                      JOptionPane.showMessageDialog(this,
                    "Xoá người dùng thành công",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                    );
                resetDataEmpty();
                loadDatas("");
                }else {
                      // lỗi ở csdl
            JOptionPane.showMessageDialog(this,
                "Xoá người dùng thật bại",
                "Inane warning",
                JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(this,
                "Xoá người dùng thật bại",
                "Inane warning",
                JOptionPane.ERROR_MESSAGE);
                System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }else {
              JOptionPane.showMessageDialog(this, // this -> from của mình
                "Vui lòng chọn người dùng cần xoá", // message
                "Cảnh báo", // title message
                JOptionPane.WARNING_MESSAGE);// type error(icon)
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void JTableNhanVienAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTableNhanVienAncestorAdded
    }//GEN-LAST:event_JTableNhanVienAncestorAdded

    private void JTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableNhanVienMouseClicked
             int row =  JTableNhanVien.getSelectedRow();// cột nó sẽ từ từ 0
             Integer id = (Integer) JTableNhanVien.getValueAt(row, 0); // column trong JTable bắt đầu từ 0
             String ho_ten = (String) JTableNhanVien.getValueAt(row, 1); 
             String dia_chi = (String) JTableNhanVien.getValueAt(row, 2); 
             String gioi_tinh = (String) JTableNhanVien.getValueAt(row, 3); 
             Date ngay_sinh = (Date) JTableNhanVien.getValueAt(row, 4); 
             String so_cmnd = (String) JTableNhanVien.getValueAt(row, 5); 
             Date ngay_vao_lam = (Date) JTableNhanVien.getValueAt(row, 6); 
             txtHoTen.setText(ho_ten);
             txtDiaChi.setText(dia_chi);
             ComboGioiTinh.setSelectedItem(gioi_tinh);
             if (ngay_sinh != null) {
                 txtNgaySinh.setText(ngay_sinh.toString());
             }
             if (ngay_vao_lam != null) {
                 txtNgayVaoLam.setText(ngay_vao_lam.toString());    
             }
             txtSoCmnd.setText(so_cmnd);
             IdNhanVien = id;
    }//GEN-LAST:event_JTableNhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new QuanLyNhanVien().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(QuanLyNhanVien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboGioiTinh;
    private javax.swing.JTable JTableNhanVien;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSoCmnd;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
